### ISSUE TITLE
many "recipe for target 'objs/XXX.o' failed"

### ISSUE THREAD

**Issue by xywang-zju** [adobe/sbmc#14]
my system is windows10,and I download Docker Desktop from docker official website,I think all is ok,but it appears some issues like "recipe for target 'objs/XXX.o' failed"when I run your Dockerfile. details:
 First I download the sbmc code,and I put it in my E:\pythonProject\sbmc-master\sbmc-master,
and in the ./dockerfiles directory,I remove cuda-sbmc.dockerfile file,and rename cpu-sbmc.dockerfile to Dockerfile,ensure only a Dockerfile in ./dockerfiles directory,and in CMD,
using command "**docker build -t ubuntu:16.04 -f ./dockerfiles/Dockerfile .**",Note the . at the end
results:
*********************************************************************************
E:\pythonProject\sbmc-master\sbmc-master> docker build -t ubuntu:16.04 -f ./dockerfiles/Dockerfile .
Sending build context to Docker daemon  2.517MB
Step 1/42 : FROM ubuntu:16.04
 ---> 5f2bf26e3524
Step 2/42 : MAINTAINER Michael Gharbi <mgharbi@adobe.com>
 ---> Using cache
 ---> 8af92dd3ac0e
Step 3/42 : RUN apt-get upgrade
 ---> Using cache
 ---> 237df2f19a56
Step 4/42 : RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
 ---> Using cache
 ---> 0cfb1c3f67a0
Step 5/42 : RUN apt-get install -y curl
 ---> Using cache
 ---> 29745fa35500
Step 6/42 : RUN apt-get install -y         build-essential         vim         git         bash         liblz4-dev         libopenexr-dev         bison         libomp-dev         cmake         flex         qt5-default         libeigen3-dev         wget         unzip         libncurses5-dev
 ---> Using cache
 ---> 20a56ef1270f
Step 7/42 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 7e34d52c71c2
Step 8/42 : RUN mkdir -p /sbmc_app /sbmc_app/output /sbmc_app/data
 ---> Using cache
 ---> 9f189b99f218
Step 9/42 : COPY pbrt_patches /sbmc_app/patches
 ---> Using cache
 ---> ff7485b92471
Step 10/42 : WORKDIR /sbmc_app
 ---> Using cache
 ---> 758bcd09eaaf
Step 11/42 : RUN git clone https://github.com/mmp/pbrt-v2.git pbrt_tmp
 ---> Using cache
 ---> 56050147aa8a
Step 12/42 : RUN cd pbrt_tmp && git checkout e6f6334f3c26ca29eba2b27af4e60fec9fdc7a8d
 ---> Using cache
 ---> acbe48063275
Step 13/42 : RUN mv pbrt_tmp/src pbrt
 ---> Using cache
 ---> 79c6e5f47092
Step 14/42 : RUN rm -rf pbrt_tmp
 ---> Using cache
 ---> 1c4f9e42ce3a
Step 15/42 : RUN patch -d pbrt -p1 -i /sbmc_app/patches/sbmc_pbrt.diff
 ---> Using cache
 ---> d2b754aec000
Step 16/42 : RUN cd pbrt && make -j
 ---> Running in 977fcbb4626c
/bin/mkdir -p bin objs
Building object objs/main_pbrt.o
Building object objs/core_parallel.o
Building object objs/core_intersection.o
Building object objs/core_volume.o
Building object objs/core_targa.o
Building object objs/core_transform.o
Building object objs/core_spectrum.o
Building object objs/core_imageio.o
Building object objs/core_scene.o
Building object objs/core_timer.o
Building object objs/core_film.o
Building object objs/core_memory.o
Building object objs/core_shape.o
Building object objs/core_quaternion.o
Building object objs/core_integrator.o
Building object objs/core_samplerecord.o
Building object objs/core_sh.o
......
......
......
Makefile:117: recipe for target 'objs/core_spectrum.o' failed
Makefile:117: recipe for target 'objs/core_volume.o' failed
Makefile:117: recipe for target 'objs/core_filter.o' failed
Makefile:109: recipe for target 'objs/accelerators_bvh.o' failed
Makefile:125: recipe for target 'objs/film_image.o' failed
Makefile:133: recipe for target 'objs/integrators_pathkpcn.o' failed
Makefile:137: recipe for target 'objs/lights_infinite.o' failed
Makefile:137: recipe for target 'objs/lights_projection.o' failed
Makefile:145: recipe for target 'objs/materials_plastic.o' failed
Makefile:129: recipe for target 'objs/filters_mitchell.o' failed
Makefile:129: recipe for target 'objs/filters_triangle.o' failed
Makefile:129: recipe for target 'objs/filters_gaussian.o' failed
Makefile:149: recipe for target 'objs/renderers_metropolis.o' failed
Makefile:153: recipe for target 'objs/samplers_stratified.o' failed
Makefile:157: recipe for target 'objs/shapes_loopsubdiv.o' failed
Makefile:145: recipe for target 'objs/materials_matte.o' failed
Makefile:157: recipe for target 'objs/shapes_heightfield.o' failed
Makefile:113: recipe for target 'objs/cameras_orthographic.o' failed
Makefile:113: recipe for target 'objs/cameras_environment.o' failed
Makefile:161: recipe for target 'objs/textures_checkerboard.o' failed
Makefile:133: recipe for target 'objs/integrators_path.o' failed
Makefile:117: recipe for target 'objs/core_film.o' failed
Makefile:133: recipe for target 'objs/integrators_glossyprt.o' failed
Makefile:129: recipe for target 'objs/filters_sinc.o' failed
Makefile:145: recipe for target 'objs/materials_substrate.o' failed
Makefile:165: recipe for target 'objs/volumes_volumegrid.o' failed
***********************************************************************************
I don't know what happened,the ./dockerfiles/Dockerfile is:
"
FROM ubuntu:16.04
MAINTAINER Michael Gharbi <mgharbi@adobe.com>

RUN apt-get upgrade
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y curl
RUN apt-get install -y \
        build-essential \
        vim \
        git \
        bash \
        liblz4-dev \
        libopenexr-dev \
        bison \
        libomp-dev \
        cmake \
        flex \
        qt5-default \
        libeigen3-dev \
        wget \
        unzip \
        libncurses5-dev

SHELL ["/bin/bash", "-c"]

RUN mkdir -p /sbmc_app /sbmc_app/output /sbmc_app/data
COPY pbrt_patches /sbmc_app/patches

WORKDIR /sbmc_app

RUN git clone https://github.com/mmp/pbrt-v2.git pbrt_tmp
RUN cd pbrt_tmp && git checkout e6f6334f3c26ca29eba2b27af4e60fec9fdc7a8d
RUN mv pbrt_tmp/src pbrt
RUN rm -rf pbrt_tmp

RUN patch -d pbrt -p1 -i /sbmc_app/patches/sbmc_pbrt.diff
**RUN cd pbrt && make -j**
...
...
...
"
when **RUN cd pbrt && make -j** ,Caused the problem.

**Comment by mgharbi** [comment]
Unfortunately, I do not have a windows machine currently to replicate this. I only tested the build on Ubuntu and OSX. 
The PBRT build is only required if you want to generate your own data though.
