### ISSUE TITLE
Broken links to previous methods

### ISSUE THREAD

**Issue by MKimiSH** [adobe/sbmc#16]
`cvc.ucsb.edu` seems to be unreachable to me, which hosts two previous methods: `Sen2011` and `Kalantari2015`). This seems to be a server issue, but I still would like to file an issue here because it also breaks the `make docker_build` command which is the first step to setting up the docker environment.

**Comment by mgharbi** [comment]
Thanks for pointing this out, this is unfortunate.

**Comment by mgharbi** [comment]
2ca0b3e79c0d90236da61dfc95de7acfab0299ee should fix it
