### ISSUE TITLE
 undefined reference to `typeinfo for Halide::Internal::GeneratorOutputBase'

### ISSUE THREAD

**Issue by gengrz123** [adobe/sbmc#17]
when I use setup.py, I  get the error.
![sendpix0](https://user-images.githubusercontent.com/26324318/87557618-b33d3000-c6ea-11ea-82c5-3f8abf883664.jpg)

**Comment by mgharbi** [comment]
Is this using the provided Docker configuration ? if not, this might come from a Halide version mismatch. https://github.com/adobe/sbmc/blob/2ca0b3e79c0d90236da61dfc95de7acfab0299ee/dockerfiles/cuda-sbmc.dockerfile#L93

**Comment by gengrz123** [comment]
> Is this using the provided Docker configuration ? if not, this might come from a Halide version mismatch.
> 
> https://github.com/adobe/sbmc/blob/2ca0b3e79c0d90236da61dfc95de7acfab0299ee/dockerfiles/cuda-sbmc.dockerfile#L93

Thank you very much!

**Comment by gengrz123** [comment]
> Is this using the provided Docker configuration ? if not, this might come from a Halide version mismatch.
> 
> https://github.com/adobe/sbmc/blob/2ca0b3e79c0d90236da61dfc95de7acfab0299ee/dockerfiles/cuda-sbmc.dockerfile#L93

Thank you very much!
