### ISSUE TITLE
make test error. "NameError: name 'ops' is not defined"

### ISSUE THREAD

**Issue by 1003581** [adobe/sbmc#20]
Hello,I successfully created the image follow your installation process ,but an error was reported when run 'make test'. Also  this error was reported when I use ' python scripts/denoise.py'  . And I'm already installed 'halide'  successfully.  I have not idea about this problem, I need your help.

    @staticmethod
    def forward(ctx, data, weights):
        bs, c, h, w = data.shape
        output = data.new()
        sum_w = data.new()
        output.resize_as_(data)
        sum_w.resize_(bs, h, w)
        if _is_cuda(data, weights):
            ops.kernel_weighting_cuda_float32(data, weights, output, sum_w)
            NameError: name 'ops' is not defined
sbmc/functions.py:96: NameError

![image](https://user-images.githubusercontent.com/31990017/100973654-e5eea480-3575-11eb-894f-ba785eac4ce4.png)

**Comment by mgharbi** [comment]
Thanks for sharing this, I'll try to have a look next week. What platform are you running on?

**Comment by 1003581** [comment]
> Thanks for sharing this, I'll try to have a look next week. What platform are you running on?
My platform 
![image](https://user-images.githubusercontent.com/31990017/101737131-6c1f6380-3aff-11eb-8b8c-1f75200fd41c.png)

**Comment by 1003581** [comment]
> Thanks for sharing this, I'll try to have a look next week. What platform are you runnin

**Comment by 1003581** [comment]
> Thanks for sharing this, I'll try to have a look next week. What platform are you running on?

**Comment by mgharbi** [comment]
somehow the halide_ops must have failed to build or not be in your path: see here https://github.com/adobe/sbmc/blob/cf02dfdfabec9ac35fd439880b194a5218dd4119/sbmc/functions.py#L25

I could not reproduce this issue on Linux.
