### ISSUE TITLE
URL "http://cgg-zwicker.inf.unibe.ch/downloads/nlm-code-data.zip" is down

### ISSUE THREAD

**Issue by nailtu30** [adobe/sbmc#24]
Hello, the URL "http://cgg-zwicker.inf.unibe.ch/downloads/nlm-code-data.zip" is down. I cannot get the file when I run `make docker_build` for `cuda-sbmc.dockerfile` (65 line).  Can I just comment it? Or can anybody provide it?

**Comment by mgharbi** [comment]
You can safely comment this out, it's just a baseline for comparisons.

**Comment by nailtu30** [comment]
ok, thanks a lot
